#!/usr/bin/env python3
"""Add a folder of photos to the site.
usage:  python3 tools/add-photos.py "/path/to/original photos" <project-id>
Creates assets/img/<project-id>/{xl,md,sm}/<project-id>-NN.jpg in filename order,
bakes EXIF orientation into the pixels, strips all metadata (incl. GPS), writes
mapping.txt and regenerates assets/js/dims.js.  Needs only macOS `sips`."""
import sys, os, struct, subprocess, json, re
def orient(path):
    data=open(path,'rb').read(256*1024)
    if data[:2]!=b'\xff\xd8': return 0
    i=2
    while i<len(data)-4:
        if data[i]!=0xFF: break
        m=data[i+1]; size=struct.unpack('>H',data[i+2:i+4])[0]
        if m==0xE1 and data[i+4:i+10]==b'Exif\x00\x00':
            t=data[i+10:i+2+size]; end='>' if t[:2]==b'MM' else '<'
            ifd=struct.unpack(end+'I',t[4:8])[0]; n=struct.unpack(end+'H',t[ifd:ifd+2])[0]
            for k in range(n):
                e=ifd+2+k*12
                if struct.unpack(end+'H',t[e:e+2])[0]==0x0112: return struct.unpack(end+'H',t[e+8:e+10])[0]
            return 0
        if m in (0xDA,0xD9): break
        i+=2+size
    return 0
def strip(path):
    data=open(path,'rb').read()
    if data[:2]!=b'\xff\xd8': return
    out=bytearray(b'\xff\xd8'); i=2
    while i<len(data)-1:
        if data[i]!=0xFF: out+=data[i:]; break
        m=data[i+1]
        if m==0xDA: out+=data[i:]; break
        size=struct.unpack('>H',data[i+2:i+4])[0]
        if m not in (0xE1,0xE3,0xE4,0xE5,0xEC,0xED,0xEE,0xFE): out+=data[i:i+2+size]
        i+=2+size
    open(path,'wb').write(out)
def convert(src,dst,size,q):
    subprocess.run(['sips','-Z',str(size),'-s','format','jpeg','-s','formatOptions',str(q),src,'--out',dst],check=True,capture_output=True)
    rot={3:180,6:90,8:270}.get(orient(dst))
    if rot: subprocess.run(['sips','-r',str(rot),dst],check=True,capture_output=True)
    strip(dst)
def dims_js(root):
    dims={}
    for pid in sorted(os.listdir(root)):
        md=os.path.join(root,pid,"md")
        if not os.path.isdir(md): continue
        for f in sorted(os.listdir(md)):
            if not f.endswith(".jpg"): continue
            out=subprocess.run(["sips","-g","pixelWidth","-g","pixelHeight",os.path.join(md,f)],capture_output=True,text=True).stdout
            dims[f[:-4]]=[int(re.search(r"pixelWidth: (\d+)",out).group(1)),int(re.search(r"pixelHeight: (\d+)",out).group(1))]
    open(os.path.join(os.path.dirname(root),"js","dims.js"),"w").write("/* Generated by tools/add-photos.py: pixel size of every md image, used to pick tall tiles automatically. */\nwindow.INTRICON = window.INTRICON || {};\nwindow.INTRICON.dims = "+json.dumps(dims,separators=(",",":"))+";\n")
if __name__=="__main__":
    if len(sys.argv)!=3: print(__doc__); sys.exit(1)
    src, pid = sys.argv[1], sys.argv[2]
    here=os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    root=os.path.join(here,"assets","img"); base=os.path.join(root,pid)
    for s in ("xl","md","sm"): os.makedirs(os.path.join(base,s),exist_ok=True)
    files=sorted(f for f in os.listdir(src) if f.lower().endswith(('.jpg','.jpeg','.png')))
    with open(os.path.join(base,"mapping.txt"),"w") as m:
        for i,f in enumerate(files,1):
            n=f"{i:02d}"; m.write(f"{pid}-{n}.jpg <- {f}\n")
            for s,px,q in (("xl",2000,80),("md",1200,78),("sm",480,72)):
                convert(os.path.join(src,f),os.path.join(base,s,f"{pid}-{n}.jpg"),px,q)
            print(f"  {pid}-{n}.jpg  <-  {f}")
    dims_js(root)
    print(f"Done: {len(files)} photos in assets/img/{pid}/ — now add the project to assets/js/projects.js")
